theme = "onedark"

[editor]
mouse = false
shell = ["zsh", "-c"]
idle-timeout = 0
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
